[font]
normal.family = "PxPlus IBM VGA 8x16"
bold.family = "PxPlus IBM VGA 8x16"
italic.family = "PxPlus IBM VGA 8x16"

[colors.primary]
background = "#000000"
foreground = "#FFFFFF"

[colors.normal]
black = "#000000"
red = "#AA0000"
green = "#00AA00"
yellow = "#AAAA00"
blue = "#0000AA"
magenta = "#AA00AA"
cyan = "#00AAAA"
white = "#AAAAAA"

[colors.bright]
black = "#555555"
red = "#FF5555"
green = "#55FF55"
yellow = "#FFFF55"
blue = "#5555FF"
magenta = "#FF55FF"
cyan = "#55FFFF"
white = "#FFFFFF"

[selection]
save_to_clipboard = true
